### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by suyulin** [koute/bytehound#104]
hi,
exec this code , webUI no data.
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

void produce_leak() {
   
    char* leak = malloc(1024 * 1024);
  
}

int main() {
    while(1) {
        produce_leak();
        sleep(2);  
    }

    return 0;
}

```
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/6275411/220515333-8295905f-c40f-4be0-9dc5-f0bafcadab9d.png">

[memory-profiling_memory_leak_1677035948_66779.txt](https://github.com/koute/bytehound/files/10799800/memory-profiling_memory_leak_1677035948_66779.txt)

**Comment by lee666-lee** [comment]
@suyulin hi, I just met the same problem. Have you worked it out???

**Comment by suyulin** [comment]
> @suyulin hi, I just met the same problem. Have you worked it out???

I have no idea , you can test real example app

**Comment by lee666-lee** [comment]
@suyulin thx
