### ISSUE TITLE
Build script fails in server-core crate

### ISSUE THREAD

**Issue by v0y4g3r** [koute/bytehound#107]
# What happens
Run `cargo build` and the build script fails

```bash
root@290e2636cf7d:~/bytehound/server-core# cargo build
   Compiling server-core v0.11.0 (/root/bytehound/server-core)
error: failed to run custom build command for `server-core v0.11.0 (/root/bytehound/server-core)`

Caused by:
  process didn't exit successfully: `/root/bytehound/target/debug/build/server-core-55f408a8d9b57e14/build-script-build` (exit status: 101)
  --- stdout
  ....
  3.4.1
  v12.22.9
  ➤ YN0000: parcel
  ➤ YN0000: Done in 0s 15ms
  bin path:  "➤ YN0000: parcel\n➤ YN0000: Done in 0s 15ms"

  --- stderr
  thread 'main' panicked at 'cannot launch a child process to build the WebUI: Os { code: 2, kind: NotFound, message: "No such file or directory" }', server-core/build.rs:148:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# The problem
`server-core/build.rs` uses `yarn bin` to get the bin dirctory of executables in webui so that the build script can find the path of `parcel` command:
https://github.com/koute/bytehound/blob/acce3bce127705ea8c840767ed351229a3c2738c/server-core/build.rs#L118-L136

This works in [classic yarn](https://classic.yarnpkg.com/en/docs/cli/bin) since it returns the clean path of `webui/node_modules/.bin`. But latest yarn will give you something like:

```bash
root@290e2636cf7d:~/bytehound/webui# yarn bin
➤ YN0000: parcel
➤ YN0000: Done in 0s 14ms
```
So the next stop which tries to run parcel command will definitely fail:
https://github.com/koute/bytehound/blob/acce3bce127705ea8c840767ed351229a3c2738c/server-core/build.rs#L147

# The fix

Instead of concatenating path, we can directly run `yarn bin parcel` command to get the executable path of parcel:

```bash
$ yarn bin parcel
/root/byteh/bytehound/webui/node_modules/parcel/lib/bin.js
```

If you don't mind, maybe I can help to fix this issue.

# Environment
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

$ node --version
v19.8.0

$ yarn -v
3.4.1

$ cargo -V
cargo 1.66.0-nightly (b8f30cb23 2022-10-10)
```

**Comment by koute** [comment]
> If you don't mind, maybe I can help to fix this issue.

Sounds good to me!

**Comment by Adoni5** [comment]
@cole-miller's solution worked for me with the following additional steps - 

1. Edit package.json

```json

```
