### ISSUE TITLE
Does the bytehound have a limit on the dat file size?

### ISSUE THREAD

**Issue by harlanc** [koute/bytehound#62]
My dat file is about  6.0G, and encounter the following error:

      [2021-12-16T08:26:08Z INFO  server_core] Trying to load "memory-profiling_test-exe_1639640943_16894.dat"...
     Killed

**Comment by koute** [comment]
There's no limit. You're just running out of memory.

Either use the `strip` subcommand to cut down the data file's size, install more RAM, or enable a big swapfile on your SSD.
