### ISSUE TITLE
thread_local_const_init is being stabilized

### ISSUE THREAD

**Issue by gagbo** [koute/bytehound#63]
Hi,

Currently (on 1.59-nightly), bytehound doesn't compile because of the [stabilization of `thread_local_const_init` feature](https://github.com/rust-lang/rust/pull/91355):

```
error[E0635]: unknown feature `thread_local_const_init`
 --> preload/src/lib.rs:1:12
  |
1 | #![feature(thread_local_const_init)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `bytehound-preload` due to previous error
```

The feature line should be removed from the code from now on I think.

Cheers,
Gerry

**Comment by koute** [comment]
Correct. Done.

**Comment by Taopper** [comment]
How to solve it？Thank you

**Comment by gagbo** [comment]
clone the repo, pull master and build from source
