### ISSUE TITLE
Attach to a already running application?

### ISSUE THREAD

**Issue by Enter-tainer** [koute/bytehound#77]
Is it possible for bytehound to analyze an already running application? It will be beneficial to diagnose memory leaks.

**Comment by koute** [comment]
It is not.

It would be possible by dynamically injecting an `.so` into an already running application and manually patching the memory to hook into the memory allocation calls. I currently have no plans of implementing anything like that though.

**Comment by Enter-tainer** [comment]
Thank you for your reply!
