### ISSUE TITLE
It doesn't work with 0.9.32-c71e872afed 

### ISSUE THREAD

**Issue by kogeler** [koute/bytehound#95]
The 0.9.0 version doesn't work with the latest binary release - 0.9.32-c71e872afed.
Logs are:
```
💾 Database: RocksDb at /opt/kusama-rpc/chains/ksmcc3/db/full
INFO main sc_cli::runner: ⛓  Native runtime: kusama-9320 (parity-kusama-0.tx15.au2)
thread '<unnamed>' panicked at 'not yet implemented: _rjem_aligned_alloc', preload/src/api.rs:699:5
```

ENV variables:
```
MEMORY_PROFILER_OUTPUT="/opt/logs/profiling_%e_%t_%p.dat"
MEMORY_PROFILER_LOGFILE="/opt/logs/profiling_%e_%t_%p.txt"
MEMORY_PROFILER_LOG="info"
MEMORY_PROFILER_CULL_TEMPORARY_ALLOCATIONS="1"
MEMORY_PROFILER_TEMPORARY_ALLOCATION_LIFETIME_THRESHOLD="120000"
LD_PRELOAD="/home/parity/bin/libbytehound.so"
```

**Comment by koute** [comment]
Yes, only the version on `master` has the necessary fixes to work. I haven't yet released it as 0.10. Until I do that for now if you want to use it and don't want to compile it yourself there's a prebuilt binary available [here](https://github.com/paritytech/devops/issues/1861#issuecomment-1282586142).
